spring.config.import=optional:file:.env[.properties]

spring.application.name=bookstore

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookstore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bookstore}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:w+QL/vZfLL429WbS+kU/r/fwg0Y0NSfCvBPJzXF30yQ=}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
